import type { ITheme } from "@xterm/xterm";

// Colors: generated `embedded_ghostty_themes.rs` entry "GitHub Dark";
// selected by apps/desktop/src/shared_settings.rs, generated by apps/desktop/build.rs, and
// consumed by apps/desktop/src/terminal_gpui_engine.rs.
export const GHOSTTY_DEFAULT_THEME = {
  background: "#101216",
  foreground: "#8b949e",
  cursor: "#c9d1d9",
  cursorAccent: "#101216",
  selectionBackground: "#3b5070",
  selectionForeground: "#ffffff",
  black: "#000000",
  red: "#f78166",
  green: "#56d364",
  yellow: "#e3b341",
  blue: "#6ca4f8",
  magenta: "#db61a2",
  cyan: "#2b7489",
  white: "#ffffff",
  brightBlack: "#4d4d4d",
  brightRed: "#f78166",
  brightGreen: "#56d364",
  brightYellow: "#e3b341",
  brightBlue: "#6ca4f8",
  brightMagenta: "#db61a2",
  brightCyan: "#2b7489",
  brightWhite: "#ffffff",
} satisfies ITheme;
